version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  web:
    build: .
    environment:
      - DATABASE_NAME=lol
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Arigato123*
      - DATABASE_HOST=44.201.235.15
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
