# Generated by Django 4.2.6 on 2023-10-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.BigIntegerField(help_text='Game identifier', unique=True, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_id',
            field=models.BigIntegerField(help_text='Id League', unique=True, verbose_name='Id League'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.BigIntegerField(help_text='Player identifier', unique=True, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.BigIntegerField(help_text='Team ForeignKey', unique=True, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.BigIntegerField(help_text='Tournament ForeignKey', unique=True, verbose_name='Tournament Id'),
        ),
    ]
