# Generated by Django 4.2.6 on 2023-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_game_game_id_alter_league_league_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(blank=True, help_text='Stage type', max_length=255, null=True, verbose_name='Type'),
        ),
    ]
