# Generated by Django 4.2.5 on 2023-09-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='idLeague',
            field=models.BigIntegerField(verbose_name='Id League'),
        ),
    ]
