# Generated by Django 4.2.6 on 2023-10-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_stage_stage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMode',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('match_mode_pk', models.AutoField(db_column='match_mode_pk', primary_key=True, serialize=False)),
                ('match_mode_name', models.CharField(max_length=50, verbose_name='Match mode name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('match_state_pk', models.AutoField(db_column='match_state_pk', primary_key=True, serialize=False)),
                ('match_state_name', models.CharField(max_length=50, verbose_name='Match state name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchStrategy',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('match_strategy_pk', models.AutoField(db_column='match_strategy_pk', primary_key=True, serialize=False)),
                ('match_strategy_name', models.CharField(max_length=50, verbose_name='Match strategy name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('match_type_pk', models.AutoField(db_column='match_type_pk', primary_key=True, serialize=False)),
                ('match_type_name', models.CharField(max_length=50, verbose_name='Match type name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='match_mode',
            field=models.ForeignKey(help_text='Match mode', on_delete=django.db.models.deletion.DO_NOTHING, to='base.matchmode'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_state',
            field=models.ForeignKey(help_text='Match state', on_delete=django.db.models.deletion.DO_NOTHING, to='base.matchstate'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_strategy',
            field=models.ForeignKey(help_text='Match strategy', on_delete=django.db.models.deletion.DO_NOTHING, to='base.matchstrategy', verbose_name='Strategy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.matchtype'),
        ),
    ]
