# Generated by Django 4.2.5 on 2023-09-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_league_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='darkImage',
            field=models.SlugField(max_length=255, verbose_name='Dark Image'),
        ),
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.SlugField(max_length=500, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='league',
            name='lightImage',
            field=models.SlugField(max_length=255, verbose_name='Light Image'),
        ),
    ]
