# Generated by Django 4.2.6 on 2023-10-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_matchmode_matchstate_matchstrategy_matchtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionName',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('section_name_pk', models.AutoField(db_column='section_name_pk', help_text='Primary key of the table', primary_key=True, serialize=False, verbose_name='Primary key of the table')),
                ('section_name', models.CharField(help_text='Section name', max_length=50, verbose_name='Section Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageName',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('stage_name_pk', models.AutoField(db_column='stage_name_pk', help_text='Primary key of the table', primary_key=True, serialize=False, verbose_name='Primary key of the table')),
                ('stage_name_name', models.CharField(help_text='Stage name', max_length=50, verbose_name='Stage name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageSlug',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('stage_slug_pk', models.AutoField(db_column='stage_slug_pk', help_text='Primary key of the table', primary_key=True, serialize=False, verbose_name='Primary key of the table')),
                ('stage_slug_slug', models.CharField(help_text='Stage type name', max_length=50, verbose_name='Stage slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('created_date', models.DateTimeField(editable=False, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(verbose_name='Modification Date')),
                ('stage_type_pk', models.AutoField(db_column='stage_type_pk', help_text='Primary key of the table', primary_key=True, serialize=False, verbose_name='Primary key of the table')),
                ('stage_type_name', models.CharField(help_text='Stage type name', max_length=50, verbose_name='Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.ForeignKey(help_text='Section name', on_delete=django.db.models.deletion.CASCADE, to='base.sectionname', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.ForeignKey(help_text='Stage name', on_delete=django.db.models.deletion.DO_NOTHING, to='base.stagename', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_slug',
            field=models.ForeignKey(help_text='Stage slug', on_delete=django.db.models.deletion.DO_NOTHING, to='base.stageslug', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.ForeignKey(blank=True, help_text='Stage type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.stagetype', verbose_name='Type'),
        ),
    ]
