# Generated by Django 4.2.6 on 2023-10-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_match_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='section_id',
            field=models.ForeignKey(db_column='section_pk', default=1, help_text='Section ForeignKey', on_delete=django.db.models.deletion.CASCADE, to='base.section', verbose_name='Section Detail'),
            preserve_default=False,
        ),
    ]
