# Generated by Django 4.2.5 on 2023-09-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_league_darkimage_alter_league_lightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='darkImage',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Dark Image'),
        ),
        migrations.AlterField(
            model_name='league',
            name='lightImage',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Light Image'),
        ),
    ]
