# Generated by Django 4.2.5 on 2023-09-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_tournament_alter_league_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='leagueId',
            new_name='idLeague',
        ),
    ]
