# Generated by Django 4.2.5 on 2023-09-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_leagueid_tournament_idleague'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('idTeam', models.BigIntegerField(verbose_name='Id Team')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('acronym', models.CharField(max_length=255, verbose_name='Acronym')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='endDate',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='startDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
