# Generated by Django 4.2.5 on 2023-09-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_teams_alter_tournament_enddate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
