# Generated by Django 4.2.5 on 2023-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_teams_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('idPlayer', models.BigIntegerField(verbose_name='Id Player')),
                ('idTeam', models.BigIntegerField(verbose_name='Team')),
                ('handle', models.CharField(max_length=16, verbose_name='Handle')),
                ('name', models.CharField(max_length=18, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='idLeague',
            field=models.BigIntegerField(verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='idTeam',
            field=models.BigIntegerField(verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='idLeague',
            field=models.BigIntegerField(verbose_name='League'),
        ),
    ]
