# Generated by Django 4.2.5 on 2023-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_player_alter_league_idleague_alter_team_idteam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='idTeam',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Team'),
        ),
    ]
