# Generated by Django 4.2.5 on 2023-09-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_player_idteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='idPlayer',
            field=models.BigIntegerField(verbose_name='Player'),
        ),
    ]
