# Generated by Django 4.2.5 on 2023-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_player_idplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='idTeam',
            field=models.BigIntegerField(null=True, verbose_name='Team'),
        ),
    ]
