# Generated by Django 4.2.5 on 2023-09-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_player_idteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
