# Generated by Django 4.2.5 on 2023-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('idPlayer', models.BigIntegerField(verbose_name='Player')),
                ('idTeam', models.BigIntegerField(null=True, verbose_name='Team')),
                ('handle', models.CharField(max_length=16, verbose_name='Handle')),
                ('name', models.CharField(max_length=18, verbose_name='Name')),
            ],
        ),
    ]
