# Generated by Django 4.2.5 on 2023-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='idTeam',
            field=models.BigIntegerField(verbose_name='Team'),
        ),
    ]
