# Generated by Django 4.2.5 on 2023-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_player_idteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
    ]
