# Generated by Django 4.2.5 on 2023-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(auto_created=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='player',
            name='idPlayer',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Player'),
        ),
    ]
