# Generated by Django 4.2.5 on 2023-09-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_league_priority_alter_player_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
