# Generated by Django 4.2.5 on 2023-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('idPlayer', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Player')),
                ('idTeam', models.BigIntegerField(verbose_name='Team')),
                ('handle', models.CharField(max_length=16, verbose_name='Handle')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
    ]
