# Generated by Django 4.2.5 on 2023-09-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game')),
                ('idParticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player', verbose_name='Player')),
            ],
        ),
    ]
