# Generated by Django 4.2.5 on 2023-09-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_gamedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetail',
            old_name='idParticipant',
            new_name='idPlayer',
        ),
    ]
