# Generated by Django 4.2.5 on 2023-09-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_idparticipant_gamedetail_idplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idPlayer',
            field=models.BigIntegerField(verbose_name='Player'),
        ),
    ]
