# Generated by Django 4.2.5 on 2023-09-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_gamedetail_idplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idGame',
            field=models.BigIntegerField(verbose_name='Game'),
        ),
    ]
