# Generated by Django 4.2.5 on 2023-09-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_gamedetail_idgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='idPlayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player', verbose_name='Player'),
        ),
    ]
