# Generated by Django 4.2.5 on 2023-09-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_gamedetail_idgame_alter_gamedetail_idplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='idPlayer',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='idParticipant',
            field=models.ForeignKey(db_column='IdPlayer', default=1, on_delete=django.db.models.deletion.CASCADE, to='base.player', verbose_name='Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='idGame',
            field=models.ForeignKey(db_column='IdGame', on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game'),
        ),
    ]
