# Generated by Django 4.2.5 on 2023-09-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_gamedetail_idplayer_gamedetail_idparticipant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetail',
            old_name='idParticipant',
            new_name='idPlayer',
        ),
    ]
