# Generated by Django 4.2.5 on 2023-09-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_gamedetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='playerMatch',
            field=models.BooleanField(default=True, verbose_name='Player equal to player table'),
        ),
    ]
