# Generated by Django 4.2.5 on 2023-09-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_gamedetail_playermatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idPlayer',
            field=models.BigIntegerField(verbose_name='Player'),
        ),
    ]
