# Generated by Django 4.2.5 on 2023-09-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_gamedetail_idplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='id',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='idGameDetail',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='GameDetail'),
            preserve_default=False,
        ),
    ]
