# Generated by Django 4.2.5 on 2023-09-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_gamedetail_id_gamedetail_idgamedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idPlayer',
            field=models.ForeignKey(db_column='IdPlayer', on_delete=django.db.models.deletion.CASCADE, to='base.player', verbose_name='Player'),
        ),
    ]
