# Generated by Django 4.2.5 on 2023-10-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_gamedetail_idplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='playerMatch',
        ),
    ]
