# Generated by Django 4.2.5 on 2023-10-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_gamedetail_playermatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='playerMatch',
            field=models.BooleanField(default=True, verbose_name='Player equal to player table'),
        ),
    ]
