# Generated by Django 4.2.5 on 2023-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_match_stage_section_matchdetail_match_idsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='idTeam',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Team'),
        ),
    ]
