# Generated by Django 4.2.5 on 2023-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_gamedetail_idgamedetail_gamedetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='id',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='idGameDetail',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='GameDetail'),
            preserve_default=False,
        ),
    ]
