# Generated by Django 4.2.5 on 2023-10-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_remove_gamedetail_idgamedetail_gamedetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game'),
        ),
    ]
