# Generated by Django 4.2.5 on 2023-10-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(max_length=255, null=True, verbose_name='Type'),
        ),
    ]
