# Generated by Django 4.2.5 on 2023-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_stage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='idTournament',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, verbose_name='Id'),
            preserve_default=False,
        ),
    ]
