# Generated by Django 4.2.5 on 2023-10-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_tournament_id_tournament_idtournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
