# Generated by Django 4.2.5 on 2023-10-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_stage_idtournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='idTournament',
        ),
    ]
