# Generated by Django 4.2.5 on 2023-10-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_stage_idtournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='idGame',
            field=models.ForeignKey(db_column='idGame', on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game'),
        ),
    ]
