# Generated by Django 4.2.5 on 2023-10-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_gamedetail_idgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='idStage',
            field=models.ForeignKey(db_column='idStage', on_delete=django.db.models.deletion.DO_NOTHING, to='base.stage', verbose_name='Stage'),
        ),
    ]
