# Generated by Django 4.2.5 on 2023-10-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_section_idstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='idSection',
            field=models.ForeignKey(db_column='idSection', on_delete=django.db.models.deletion.DO_NOTHING, to='base.section', verbose_name='Section Detail'),
        ),
    ]
