# Generated by Django 4.2.5 on 2023-10-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_match_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetail',
            name='idTeam',
            field=models.ForeignKey(db_column='idTeam', on_delete=django.db.models.deletion.DO_NOTHING, to='base.team', verbose_name='Team'),
        ),
    ]
