# Generated by Django 4.2.5 on 2023-10-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_matchdetail_idteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='idTournament',
            field=models.BigIntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
