# Generated by Django 4.2.5 on 2023-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_tournament_idtournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='idTournament',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
