# Generated by Django 4.2.5 on 2023-10-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_tournament_idtournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='idMatch',
        ),
        migrations.AddField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
