# Generated by Django 4.2.5 on 2023-10-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_remove_match_idmatch_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdetail',
            name='idMatch',
        ),
        migrations.RemoveField(
            model_name='matchdetail',
            name='idTeam',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchDetail',
        ),
    ]
