# Generated by Django 4.2.6 on 2023-10-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_match_matchdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='darkImage',
            new_name='league_dark_image',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='displayPriorityPosition',
            new_name='league_display_priority_position',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='displayPriorityStatus',
            new_name='league_display_priority_status',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='idLeague',
            new_name='league_id',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='image',
            new_name='league_image',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='lightImage',
            new_name='league_light_image',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='league_name',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='priority',
            new_name='league_priority',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='region',
            new_name='league_region',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='slug',
            new_name='league_slug',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='sport',
            new_name='league_sport',
        ),
    ]
