# Generated by Django 4.2.6 on 2023-10-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_rename_idgame_game_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Game'),
        ),
    ]
